apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    run: reverseproxy
spec:
  selector:
    service: reverseproxy
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP