apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: tdong2010/reverseproxy:latest
        ports: 
        - containerPort: 8080

