apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
      - name: udagram-frontend
        image: tdong2010/udagram-frontend
        ports: 
        - containerPort: 80
      - name: udagram-api-feed
        image: tdong2010/udagram-api-feed
        ports: 
        - containerPort: 80
      - name: udagram-api-user
        image: tdong2010/udagram-api-user
        ports: 
        - containerPort: 80
      - name: reverseproxy
        image: tdong2010/reverseproxy
        ports: 
        - containerPort: 80


